### ISSUE TITLE
Implement Chat Functionality with ChatGPT API

### ISSUE THREAD

**Issue by dpS1lence** [InternAcademy/CookingApp#11]
# User Story: Implement Chat Functionality with ChatGPT API

## Overview
As a user of the Cooking Chat App, I want to interact with the app through chat functionality powered by the ChatGPT API. I want to control my previous chats, send and receive images, save recipes from the chat, and specify my dietary preferences and allergies when I first chat with the app, so that my experience is personalized and tailored to my needs.

### Chat Functionality:
- [x] #20 
- [x] #19 
- Allow users to send images to the app and receive image responses.

### Chat History:
- Implement functionality for users to view and manage their previous chats.
- Allow users to revisit previous conversations and extract useful information.

### Recipe Management:
- Enable users to save recipes from their chats with the AI bot.
- Store saved recipes in the user's profile for easy access.

### Dietary Preferences and Allergies:
- During the first chat interaction, prompt users to input their dietary preferences and allergies.
- Use this information to personalize recipe recommendations and chat responses.

### User Interface:
- Ensure the chat interface is user-friendly and visually appealing.
- Provide clear options for users to save recipes and manage chat history.

### Testing:
- Write unit and integration tests for the chat functionality to ensure reliability.
- Conduct manual testing to verify the complete chat experience and user interface.

**Comment by ChrisIvanov** [comment]
I guess we can close this one as we've already merged it through another issue.
